### ISSUE TITLE
Surface an error or log message when the API key isn't found

### ISSUE THREAD

**Issue by morehavoc** [dymaptic/dy-blazor-api-core#14]
I was just experimenting with this in WASM and was using a static API key. I had the `appsettings.json` file in the wrong place and so the API key wasn't available. In this case the map just didn't load. It would be nice if there was a log message or an error of some kind so that as the developer I can tell that's what is missing.

**Comment by TimPurdum** [comment]
The latest version is surfacing this popup from Esri (and this interface does work for providing the key), so feel like this might be a moot point. Or should we still have our own error as well? @morehavoc 
<img width="948" alt="image" src="https://user-images.githubusercontent.com/17970404/190010675-0d1a869d-69ad-4a23-a233-7a23f363d0d8.png">

**Comment by TimPurdum** [comment]
OK, I was _partially_ wrong, in that you won't see that popup on our `develop` branch, because we quit trying before we get there. I am going to whip together some combination of allowing this to pass through when the API Key is missing and adding an optional warning message, that can be shut off if the devs _want_ the user to have to sign in. Still this is super helpful, as we don't need to add sign-in capabilities, and I think there are some stubs in that direction I can remove.

**Comment by morehavoc** [comment]
Is that a real OAuth workflow for sign-in?

**Comment by TimPurdum** [comment]
I believe so? It's the same sign-in you'd get from an ArcGIS website.
